version: '2'
services:
  web:
    image: fpfis/httpd-php:8.1-dev
    working_dir: ${PWD}
    ports:
      - '8080:8080'
    volumes:
      - ${PWD}:${PWD}
      # - $HOME/.composer/.auth.json:$HOME/.composer/.auth.json
    environment:
      DOCUMENT_ROOT: ${PWD}
      # By leaving these variables empty Docker Compose will set them to their host values.
      NEXTCLOUD_USER:
      NEXTCLOUD_PASS:
      GITHUB_API_TOKEN:
      GITLAB_API_TOKEN:
      QA_API_BASIC_AUTH:
      QA_WEBSITE_URL:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
      PHP_IDE_CONFIG: 'serverName=Docker'
      # For Xdebug setup, run this command in the terminal:
      # For Mac users: sudo ifconfig en0 alias 10.254.254.254 255.255.255.0
      # For Linux users: sudo ip addr add 10.254.254.254/32 dev lo label lo:1
    env_file:
      - .env

  mysql:
    image: percona/percona-server:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql:/var/lib/mysql

  selenium:
    image: selenium/standalone-chrome:4.1.3-20220405
    environment:
      - DISPLAY=:99
    ports:
      - '5900:5900'
    expose:
      - 4444

volumes:
  mysql:
